const movies = [
  {
    Title: "The Lord of the Rings: The Fellowship of the Ring",
    Year: "2001",
    Rated: "PG-13",
    Released: "19 Dec 2001",
    Runtime: "178 min",
    Genre: "Action, Adventure, Drama, Fantasy",
    Director: "Peter Jackson",
    Writer:
      "J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)",
    Actors: "Alan Howard, Noel Appleby, Sean Astin, Sala Baker",
    Plot:
      "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    Language: "English, Sindarin",
    Country: "New Zealand, USA",
    Awards: "Won 4 Oscars. Another 114 wins & 124 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "91%",
      },
      {
        Source: "Metacritic",
        Value: "92/100",
      },
    ],
    Metascore: "92",
    imdbRating: "8.8",
    imdbVotes: "1,619,534",
    imdbID: "tt0120737",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "New Line Cinema, Saul Zaentz Company, WingNut Films",
    Website: "N/A",
    Response: "True",
    Clip: "https://www.youtube.com/watch?v=rCZ3SN65kIs",
  },
  {
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi, Thriller",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
    Plot:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    Language: "English, Japanese, French",
    Country: "USA, UK",
    Awards: "Won 4 Oscars. Another 152 wins & 217 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "87%",
      },
      {
        Source: "Metacritic",
        Value: "74/100",
      },
    ],
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,003,841",
    imdbID: "tt1375666",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "Syncopy, Warner Bros.",
    Website: "N/A",
    Response: "True",
    Clip: "https://www.youtube.com/watch?v=fpXngRB-VTw",
  },
  {
    Title: "Lords of Dogtown",
    Year: "2005",
    Rated: "PG-13",
    Released: "03 Jun 2005",
    Runtime: "107 min",
    Genre: "Biography, Drama, Sport",
    Director: "Catherine Hardwicke",
    Writer: "Stacy Peralta",
    Actors: "John Robinson, Emile Hirsch, Rebecca De Mornay, William Mapother",
    Plot:
      "The film follows the surf and skateboarding trends that originated in Venice, California during the 1970's.",
    Language: "English, Spanish",
    Country: "USA, Germany",
    Awards: "1 win & 7 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDBhNGJlOTAtM2ExNi00NmEzLWFmZTQtYTZhYTRlNjJjODhmXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "55%",
      },
      {
        Source: "Metacritic",
        Value: "56/100",
      },
    ],
    Metascore: "56",
    imdbRating: "7.1",
    imdbVotes: "51,437",
    imdbID: "tt0355702",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "Indelible Pictures",
    Website: "N/A",
    Response: "True",
    Clip: "https://www.youtube.com/watch?v=FaCKRDwhXII&ab_channel=windystewart",
  },
  {
    Title: "The Dark Knight Rises",
    Year: "2012",
    Rated: "PG-13",
    Released: "20 Jul 2012",
    Runtime: "164 min",
    Genre: "Action, Adventure",
    Director: "Christopher Nolan",
    Writer:
      "Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)",
    Actors: "Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt",
    Plot:
      "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.",
    Language: "English, Arabic",
    Country: "UK, USA",
    Awards:
      "Nominated for 1 BAFTA Film Award. Another 38 wins & 101 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "87%",
      },
      {
        Source: "Metacritic",
        Value: "78/100",
      },
    ],
    Metascore: "78",
    imdbRating: "8.4",
    imdbVotes: "1,480,138",
    imdbID: "tt1345836",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "Syncopy",
    Website: "N/A",
    Response: "True",
    Clip: "https://www.youtube.com/watch?v=rDuetklFtDQ",
  },
  {
    Title: "Good Will Hunting",
    Year: "1997",
    Rated: "R",
    Released: "09 Jan 1998",
    Runtime: "126 min",
    Genre: "Drama, Romance",
    Director: "Gus Van Sant",
    Writer: "Matt Damon, Ben Affleck",
    Actors: "Matt Damon, Ben Affleck, Stellan Skarsgård, John Mighton",
    Plot:
      "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
    Language: "English",
    Country: "USA",
    Awards: "Won 2 Oscars. Another 22 wins & 60 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "97%",
      },
      {
        Source: "Metacritic",
        Value: "70/100",
      },
    ],
    Metascore: "70",
    imdbRating: "8.3",
    imdbVotes: "835,631",
    imdbID: "tt0119217",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production:
      "Miramax Films, Be Gentlemen Limited Partnership, Lawrence Bender Productions",
    Website: "N/A",
    Response: "True",
    Clip: "https://www.youtube.com/watch?v=hIdsjNGCGz4",
  },
  {
    Title: "The Road to El Dorado",
    Year: "2000",
    Rated: "PG",
    Released: "31 Mar 2000",
    Runtime: "89 min",
    Genre: "Animation, Adventure, Comedy, Family, Romance",
    Director: "Bibo Bergeron, Don Paul, Jeffrey Katzenberg",
    Writer:
      "Terry Rossio (screenplay), Ted Elliott (screenplay), Karey Kirkpatrick (additional dialogue)",
    Actors: "Kevin Kline, Kenneth Branagh, Rosie Perez, Armand Assante",
    Plot:
      "Two swindlers get their hands on a map to the fabled city of gold, El Dorado.",
    Language: "English",
    Country: "USA",
    Awards: "1 win & 12 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTEzNWIwMzctOTE1YS00YjIyLTgwZGEtMTMxZDAzNzlmODMxXkEyXkFqcGdeQXVyMjgyMDk1MzY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "48%",
      },
      {
        Source: "Metacritic",
        Value: "51/100",
      },
    ],
    Metascore: "51",
    imdbRating: "6.9",
    imdbVotes: "82,069",
    imdbID: "tt0138749",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "DreamWorks Pictures, Stardust Pictures",
    Website: "N/A",
    Response: "True",
    Clip: "https://www.youtube.com/watch?v=h3AqOR2Ru1s&ab_channel=Movieclips",
  },
  {
    Title: "The Last Samurai",
    Year: "2003",
    Rated: "R",
    Released: "05 Dec 2003",
    Runtime: "154 min",
    Genre: "Action, Drama, War",
    Director: "Edward Zwick",
    Writer:
      "John Logan (story), John Logan (screenplay), Edward Zwick (screenplay), Marshall Herskovitz (screenplay)",
    Actors: "Ken Watanabe, Tom Cruise, William Atherton, Chad Lindberg",
    Plot:
      "An American military advisor embraces the Samurai culture he was hired to destroy after he is captured in battle.",
    Language: "English, Japanese",
    Country: "USA, New Zealand, Japan",
    Awards: "Nominated for 4 Oscars. Another 21 wins & 62 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzkyNzQ1Mzc0NV5BMl5BanBnXkFtZTcwODg3MzUzMw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "66%",
      },
      {
        Source: "Metacritic",
        Value: "55/100",
      },
    ],
    Metascore: "55",
    imdbRating: "7.7",
    imdbVotes: "392,147",
    imdbID: "tt0325710",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production:
      "Cruise-Wagner Productions, Radar Pictures, Bedford Falls Productions, Warner Brothers",
    Website: "N/A",
    Response: "True",
    Clip: "https://www.youtube.com/watch?v=rSB9VJcwQsc",
  },
];

export default movies;
